### ISSUE TITLE
Create a new package for supporting django

### ISSUE THREAD

**Issue by aj3sh** [opensource-nepal/py-nepali#56]
Maintaining Django support on the `nepali` package is hectic. It isn't easy to write test cases for it. Therefore, let's create a new package `django-nepali` to support this package. This ensures that the `nepali` package is not responsible for any issues with different frameworks.

For backward compatibility, we will deprecate the support of Django templates and remove it in version 2.X.X. We will redirect the use of Django to another package through our README file.

Note: We had some Django template tag issues in version 1.0.0.

**Comment by aj3sh** [comment]
A new repository has been created: https://github.com/opensource-nepal/django-nepali. This issue will be closed once the Django package is ready for delivery and our documentation is updated accordingly.

cc: @sugat009

**Comment by aj3sh** [comment]
@sugat009, Please check this PR: https://github.com/opensource-nepal/django-nepali/pull/1 and follow up.

**Comment by sugat009** [comment]
https://github.com/opensource-nepal/django-nepali/pull/1 has been merged. So, closing this issue.

**Comment by aj3sh** [comment]
Reopening this issue as the task "For backward compatibility, we will deprecate the support of Django templates and remove it in version 2.X.X. We will redirect the use of Django to another package through our README file." are incomplete.
