### ISSUE TITLE
Write new tests for nepalidatetime with full coverage

### ISSUE THREAD

**Issue by aj3sh** [opensource-nepal/py-nepali#64]
There are tests written for `nepalidatetime`. But the tests are mostly positive test cases and don't have full code coverage. 

This task includes writing completely new tests for nepalidatetime. Also, maintain the test directory according to the package structure. For instance, for `nepali.datetime.nepalidatetime` the test will be something like this, `tests/test_datetime/test_nepalidatetime.py`

**Comment by golesuman** [comment]
I can work on this, right?

**Comment by aj3sh** [comment]
Yes, you are welcome. It would be great if you create small PRs for this issue. 🙂
